"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { Bot, Loader2, Plus, Trash2, Upload } from "lucide-react";
import { toast } from "sonner";
import { templatesApi } from "@/lib/api";
import type { TemplateCategory, WhatsappIntegration, WhatsappTemplate } from "@/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type HeaderFormat = "NONE" | "TEXT" | "IMAGE" | "VIDEO" | "DOCUMENT" | "LOCATION";
type DraftButton = { type: "QUICK_REPLY" | "URL" | "PHONE_NUMBER" | "COPY_CODE" | "VOICE_CALL"; text: string; value: string };
const blank = () => ({ name: "", language: "en_US", category: "MARKETING" as TemplateCategory, headerFormat: "NONE" as HeaderFormat, headerText: "", headerExamples: "", headerHandle: "", body: "", bodyExamples: "", footer: "", buttons: [] as DraftButton[] });

function examples(input: string) { return input.split(",").map((v) => v.trim()).filter(Boolean); }
function positionalCount(text: string) { return [...text.matchAll(/{{(\d+)}}/g)].reduce((max, m) => Math.max(max, Number(m[1])), 0); }
function componentExamples(text: string, raw: string, key: "body_text" | "header_text") {
  const count = positionalCount(text); if (!count) return undefined;
  const values = examples(raw); const filled = Array.from({ length: count }, (_, i) => values[i] || `Example ${i + 1}`);
  return key === "body_text" ? { body_text: [filled] } : { header_text: filled };
}

export function TemplateBuilder({ numbers }: { numbers: WhatsappIntegration[] }) {
  const [draft, setDraft] = useState(blank); const [selectedPhone, setSelectedPhone] = useState("");
  const [items, setItems] = useState<WhatsappTemplate[]>([]); const [busy, setBusy] = useState(false); const [aiPrompt, setAiPrompt] = useState("");
  const update = <K extends keyof ReturnType<typeof blank>>(key: K, value: ReturnType<typeof blank>[K]) => setDraft((d) => ({ ...d, [key]: value }));
  const media = ["IMAGE", "VIDEO", "DOCUMENT"].includes(draft.headerFormat);
  const bodyPreview = useMemo(() => draft.body.replace(/{{\d+}}/g, "Example"), [draft.body]);
  const load = async () => { try { setItems(await templatesApi.list(selectedPhone || undefined)); } catch (e) { toast.error(e instanceof Error ? e.message : "Could not load templates"); } };
  useEffect(() => { if (numbers.length) { setSelectedPhone((current) => current || numbers.find((n) => n.isDefault)?.whatsapp?.phoneNumberId || numbers[0]?.whatsapp?.phoneNumberId || ""); } }, [numbers]);
  useEffect(() => { if (selectedPhone) void load(); }, [selectedPhone]);
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setBusy(true); try { const { handle } = await templatesApi.uploadHeader(file, selectedPhone); update("headerHandle", handle); toast.success("Media uploaded for this template"); } catch (e) { toast.error(e instanceof Error ? e.message : "Upload failed"); } finally { setBusy(false); } };
  const components = () => {
    const result: Record<string, unknown>[] = [];
    if (draft.headerFormat === "TEXT") result.push({ type: "HEADER", format: "TEXT", text: draft.headerText, example: componentExamples(draft.headerText, draft.headerExamples, "header_text") });
    else if (media) result.push({ type: "HEADER", format: draft.headerFormat, example: { header_handle: [draft.headerHandle] } });
    else if (draft.headerFormat === "LOCATION") result.push({ type: "HEADER", format: "LOCATION" });
    result.push({ type: "BODY", text: draft.body, example: componentExamples(draft.body, draft.bodyExamples, "body_text") });
    if (draft.footer) result.push({ type: "FOOTER", text: draft.footer });
    if (draft.buttons.length) result.push({ type: "BUTTONS", buttons: draft.buttons.map((b) => b.type === "QUICK_REPLY" || b.type === "VOICE_CALL" ? { type: b.type, text: b.text } : b.type === "URL" ? { type: "URL", text: b.text, url: b.value, ...(b.value.includes("{{1}}") ? { example: ["example"] } : {}) } : b.type === "PHONE_NUMBER" ? { type: "PHONE_NUMBER", text: b.text, phone_number: b.value } : { type: "COPY_CODE", example: b.value }) });
    return result.map((c) => Object.fromEntries(Object.entries(c).filter(([, value]) => value !== undefined)));
  };
  const save = async () => { if (!draft.name || !draft.body) return toast.error("Template name and body are required"); if (media && !draft.headerHandle) return toast.error("Upload header media before submitting"); setBusy(true); try { await templatesApi.create({ phoneNumberId: selectedPhone || undefined, name: draft.name, language: draft.language, category: draft.category, parameter_format: "positional", components: components() }); toast.success("Template submitted to Meta for review"); setDraft(blank()); await load(); } catch (e) { toast.error(e instanceof Error ? e.message : "Template submission failed"); } finally { setBusy(false); } };
  const ai = async () => { if (aiPrompt.trim().length < 8) return toast.error("Describe the message you want to create"); setBusy(true); try { const generated = await templatesApi.aiDraft(aiPrompt, draft.category); const cs = generated.components || []; const header = cs.find((c: any) => c.type === "HEADER") as any; const body = cs.find((c: any) => c.type === "BODY") as any; const footer = cs.find((c: any) => c.type === "FOOTER") as any; const buttons = (cs.find((c: any) => c.type === "BUTTONS") as any)?.buttons || []; setDraft({ ...blank(), name: generated.name, language: generated.language, category: generated.category, headerFormat: header?.format || "NONE", headerText: header?.text || "", body: body?.text || "", footer: footer?.text || "", buttons: buttons.map((b: any) => ({ type: b.type, text: b.text || (b.type === "COPY_CODE" ? "Copy code" : ""), value: b.url || b.phone_number || b.example || "" })) }); toast.success("AI draft is ready to review"); } catch (e) { toast.error(e instanceof Error ? e.message : "AI draft failed"); } finally { setBusy(false); } };
  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
    <section className="space-y-5 rounded-xl border border-border bg-bg-panel p-5">
      <div className="flex flex-wrap items-end gap-3"><div className="flex-1"><Label>Connected number</Label><Select value={selectedPhone} onValueChange={setSelectedPhone}><SelectTrigger><SelectValue placeholder="Choose a number" /></SelectTrigger><SelectContent>{numbers.map((n) => <SelectItem key={n.id} value={n.whatsapp?.phoneNumberId || n.id}>{n.label || n.whatsapp?.phoneNumber || "WhatsApp number"}</SelectItem>)}</SelectContent></Select></div><div className="w-40"><Label>Category</Label><Select value={draft.category} onValueChange={(v) => update("category", v as TemplateCategory)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="MARKETING">Marketing</SelectItem><SelectItem value="UTILITY">Utility</SelectItem><SelectItem value="AUTHENTICATION">Authentication</SelectItem></SelectContent></Select></div></div>
      <div className="rounded-lg border border-brand/30 bg-brand/5 p-3"><Label>Draft with AI</Label><div className="mt-2 flex gap-2"><Input value={aiPrompt} onChange={(e) => setAiPrompt(e.target.value)} placeholder="e.g. delivery update with tracking link and support button" /><Button variant="secondary" onClick={ai} disabled={busy}><Bot className="mr-2 h-4 w-4" />Draft</Button></div></div>
      <div className="grid gap-3 sm:grid-cols-2"><div><Label>Template name</Label><Input value={draft.name} onChange={(e) => update("name", e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "_"))} placeholder="order_delivery_update" /></div><div><Label>Language</Label><Input value={draft.language} onChange={(e) => update("language", e.target.value)} /></div></div>
      <div className="space-y-3 border-t border-border pt-5"><Label>Header (optional)</Label><Select value={draft.headerFormat} onValueChange={(v) => update("headerFormat", v as HeaderFormat)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["NONE", "TEXT", "IMAGE", "VIDEO", "DOCUMENT", "LOCATION"].map((v) => <SelectItem key={v} value={v}>{v === "NONE" ? "No header" : v}</SelectItem>)}</SelectContent></Select>{draft.headerFormat === "TEXT" && <><Input value={draft.headerText} onChange={(e) => update("headerText", e.target.value)} maxLength={60} placeholder="Your order {{1}} is on its way" /><Input value={draft.headerExamples} onChange={(e) => update("headerExamples", e.target.value)} placeholder="Variable examples, comma-separated" /></>}{media && <div className="flex items-center gap-2"><Button variant="outline" asChild><label className="cursor-pointer"><Upload className="mr-2 h-4 w-4" />Upload {draft.headerFormat.toLowerCase()}<input className="hidden" type="file" accept={draft.headerFormat === "IMAGE" ? "image/*" : draft.headerFormat === "VIDEO" ? "video/*" : ".pdf,.doc,.docx"} onChange={upload} /></label></Button>{draft.headerHandle && <span className="text-xs text-emerald-600">Header media ready</span>}</div>}</div>
      <div><Label>Message body</Label><Textarea value={draft.body} onChange={(e) => update("body", e.target.value)} maxLength={1024} placeholder="Hi {{1}}, your order {{2}} is on its way." className="mt-1 min-h-28" /><Input className="mt-2" value={draft.bodyExamples} onChange={(e) => update("bodyExamples", e.target.value)} placeholder="Variable examples in order, comma-separated" /></div><div><Label>Footer (optional)</Label><Input value={draft.footer} onChange={(e) => update("footer", e.target.value)} maxLength={60} placeholder="Reply STOP to opt out" /></div>
      <div className="space-y-2 border-t border-border pt-5"><div className="flex items-center justify-between"><Label>Buttons (up to 10)</Label><Button size="sm" variant="outline" onClick={() => update("buttons", [...draft.buttons, { type: "QUICK_REPLY", text: "", value: "" }])}><Plus className="mr-1 h-4 w-4" />Add button</Button></div>{draft.buttons.map((button, index) => <div key={index} className="flex gap-2"><Select value={button.type} onValueChange={(v) => update("buttons", draft.buttons.map((b, i) => i === index ? { ...b, type: v as DraftButton["type"] } : b))}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="QUICK_REPLY">Quick reply</SelectItem><SelectItem value="URL">Website URL</SelectItem><SelectItem value="PHONE_NUMBER">Phone number</SelectItem><SelectItem value="COPY_CODE">Copy coupon code</SelectItem><SelectItem value="VOICE_CALL">WhatsApp call</SelectItem></SelectContent></Select>{button.type !== "COPY_CODE" && <Input value={button.text} onChange={(e) => update("buttons", draft.buttons.map((b, i) => i === index ? { ...b, text: e.target.value } : b))} placeholder="Button label" />}{!["QUICK_REPLY", "VOICE_CALL"].includes(button.type) && <Input value={button.value} onChange={(e) => update("buttons", draft.buttons.map((b, i) => i === index ? { ...b, value: e.target.value } : b))} placeholder={button.type === "COPY_CODE" ? "WELCOME20" : button.type === "URL" ? "https://example.com/{{1}}" : "15551234567"} />}<Button size="icon" variant="ghost" onClick={() => update("buttons", draft.buttons.filter((_, i) => i !== index))}><Trash2 className="h-4 w-4" /></Button></div>)}</div>
      <Button className="w-full" onClick={save} disabled={busy || !selectedPhone}>{busy && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Submit template to Meta</Button>
    </section>
    <aside className="space-y-5"><div className="rounded-xl border border-border bg-bg-panel p-5"><p className="text-xs font-medium uppercase text-muted-foreground">WhatsApp preview</p><div className="mt-4 rounded-lg bg-[#e9e4dc] p-3"><div className="rounded-lg bg-white p-3 text-sm shadow-sm">{draft.headerFormat === "TEXT" && <p className="mb-2 font-semibold">{draft.headerText || "Header"}</p>}{media && <div className="mb-2 flex h-28 items-center justify-center rounded bg-slate-200 text-xs text-muted-foreground">{draft.headerFormat} header</div>}<p className="whitespace-pre-wrap">{bodyPreview || "Your template message will appear here."}</p>{draft.footer && <p className="mt-2 text-xs text-muted-foreground">{draft.footer}</p>}{draft.buttons.map((b, i) => <p key={i} className="mt-2 border-t pt-2 text-center text-brand-strong">{b.text || "Copy code"}</p>)}</div></div></div><div className="rounded-xl border border-border bg-bg-panel p-5"><p className="font-medium">Submitted templates</p><div className="mt-3 space-y-2">{items.length ? items.map((t) => <div key={`${t.id}-${t.language}`} className="rounded border border-border p-2 text-sm"><div className="flex justify-between gap-2"><span className="font-medium">{t.name}</span><span className="text-xs text-muted-foreground">{t.status}</span></div><p className="mt-1 text-xs text-muted-foreground">{t.category} · {t.language}</p>{t.rejected_reason && <p className="mt-1 text-xs text-destructive">{t.rejected_reason}</p>}</div>) : <p className="text-sm text-muted-foreground">No templates found for this number.</p>}</div></div></aside>
  </div>;
}
